### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by BeInLife** [hirdbluebird/Intetics#2]
https://github.com/hirdbluebird/Intetics/blob/04048517714862ecaa7ad163c145ee3d0ea75b05/index.html#L26
Here it's better to use `const array` instead of `let array`

**Comment by BeInLife** [comment]
https://github.com/hirdbluebird/Intetics/blob/04048517714862ecaa7ad163c145ee3d0ea75b05/index.html#L59 
Same here, but truly saying, this line makes no sense. U r copying array by link, not by value.
Check `Array.from()` at MDN

**Comment by Titiaiev** [comment]
или так `let array= [ ].concat(incomingArray);`
