### ISSUE TITLE
Ты серьезно?

### ISSUE THREAD

**Issue by Roman-Kuvaldin** [hirdbluebird/Intetics#5]
Это звиздец, простите...
{"multiplier":99429,"multiplicand":98251,"product":9768998679}
Script has been executed in 211.53029999998398 seconds

1. Этот код должен выполняться менее секунды.
2. В нем огромное количество лишних операций.
3. Результат неправильный. Правильный результат такой:

RESULT: 1997667991 that is 91009 * 69143 (627 ms taken)

Первое что надо сделать - это "решетом Эратосфена" получить список простых чисел в диапазоне от 99999 до 10000. Их всего 8363. И не массив надо не резать и склеивать, а хранить в каждом элементе true или false. Само число уже определяется индексом элемента.

И перемножать уже только те числа, которые есть в этом списке. В результате код работает порядка секунды.

А еще можно хранить результат и множители в отдельных переменных, так чтобы если результат умножения меньше чем последний известный палиндром - то даже проверку на палиндром не делать.

Понятное дело, что тестовое задание ты провалил

**Comment by JaJaBinxx** [comment]
@Roman-Kuvaldin вот я, конечно, с пунктами 1-2 согласен. Но есть нюанс: 91009 * 69143 = 6292635287.
у вас в коде переполнение :D

**Comment by Roman-Kuvaldin** [comment]
Ну значит и меня не возьмут в космонавты :-(

**Comment by JaJaBinxx** [comment]
@Roman-Kuvaldin чего, ход мыслей в посте очень правильный, а от глупых ошибок никто не застрахован)

**Comment by MazharaRoman** [comment]
@JaJaBinxx @Roman-Kuvaldin, не расстраивайся в космосе писять не удобно

**Comment by JaJaBinxx** [comment]
@MazharaRoman ракуем! 🦀

**Comment by rkuvaldin** [comment]
RESULT: 999949999 that is 33211 * 30109 (5088 ms taken)
Для истины.
Так вроде правильно.

**Comment by Roman-Kuvaldin** [comment]
RESULT: 999949999 that is 33211 * 30109 (5088 ms taken)
Так вроде правильно

**Comment by Titiaiev** [comment]
> RESULT: 999949999 that is 33211 * 30109 (5088 ms taken)
> Так вроде правильно

У тебя действительно получилось за 5 сек?
На какой машине?
На JavaScript?

**Comment by MazharaRoman** [comment]
@Titiaiev на среднестатистической) 
тут та же фигня. мой прогнался за 4.

**Comment by JaJaBinxx** [comment]
@MazharaRoman @Titiaiev нашли шо обсуждать :)

**Comment by MazharaRoman** [comment]
@JaJaBinxx проснулся))

**Comment by JaJaBinxx** [comment]
@MazharaRoman кто бы говорил)))

**Comment by Titiaiev** [comment]
@MazharaRoman у меня за 7.5 сек выполняется. Вот и думаю, можно ли быстрее и как?
У тебя функция проверки на палиндром начинается с середины и к краям идёт или наоборот?

**Comment by Titiaiev** [comment]
@JaJaBinxx интересно же!

**Comment by Titiaiev** [comment]
@MazharaRoman, @JaJaBinxx посмотрите что у меня не так?
Не знаю, что там нужно улучшить. Буду рад если подскажете.
[https://github.com/Titiaiev/max_palindrom_from_multprimes](https://github.com/Titiaiev/max_palindrom_from_multprimes)
